server:
  error:
    include-stacktrace: never

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: EstudosSpringBoot
  datasource:
    url: ${DB_URL}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update